version: 2
jobs:
 build:
   machine: 
     docker_layer_caching: true
   steps:
     - checkout
     
     # build the application image
     - run: docker build . -t test-docker --build-arg DOCKER_TYPE=TEST 
      
     # run test app
     - run: docker run -it --rm test-docker timeout 60 libasyik_test       
