version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker build . -t test-docker --build-arg DOCKER_TYPE=TEST 
      

     # build the application image
     - run: docker run -it --rm test-docker libasyik_test       
