version: 2.1
orbs:
 codecov: codecov/codecov@1.0.2
jobs:
 build:
   machine: true
   steps:
     - checkout
     
     # build the application image
     - run: docker build . -t test-docker --build-arg DOCKER_TYPE=TEST 
      
     # run test app
     - run: docker run -it --rm -v ${PWD}/coverage:/mnt/coverage test-docker bash /usr/local/libasyik/tests/test_and_coverage.sh

     - codecov/upload:
         file: coverage/libasyik_test.info

